### ISSUE TITLE
mouse highlighting

### ISSUE THREAD

**Issue by tommyshem** [NicolaiSoeborg/filemanager-plugin#13]
When picking a directory with the mouse it highlights files and directorys when it should not.
This is on Linux gnome terminal.
Micro editor v1.3.3

**Comment by sum01** [comment]
Instead of highlighting the line, like in https://github.com/NicolaiSoeborg/filemanager-plugin/blob/master/filemanager.lua#L79-L80

`list` could be made "global" by puting it at the top of the plugin. Then you get `treeView.Buf.Cursor.Loc.Y` and put that into `list[y_loc + 1]` (+1 because it returns a zero-based index from Go, while Lua uses one-based indicies) to get the selection without visually selecting anything.

I already tested this and it works, but there's a small visual bug where after the click, it hightlings where your mouse was. The only solution I can think of to fix that is to change the `refreshTree` to only run after `MouseUp`, if that's possible.

**Comment by sum01** [comment]
Oh, found a possible solution for that. After a refresh we can do https://github.com/zyedidia/micro/blob/master/cmd/micro/cursor.go#L48-L49 to remove any highlighting caused by a percieved mouse drag.
