### ISSUE TITLE
Open file on right arrow

### ISSUE THREAD

**Issue by ghost** [NicolaiSoeborg/filemanager-plugin#40]
Just make opening files not only on tab (which is not intuitive, i had to read the docs) but also with right-arrow like you show a folder.

**Comment by rvi64** [comment]
#41 is a simple patch for that

**Comment by sum01** [comment]
I was required to change away from the enter key, as Micro disables the callback to the enter key when using read-only. That change was made in v3. As for why I didn't do the right key, no idea. Hopefully I, or someone else, gets around to merging that, although I would rather see a keybinding system instead of a fallback like that in the function.

**Comment by rvi64** [comment]
It's okay to make it callback-based if it's not HUGE like in case of this plugin.
But in this case as far as I know plugin has been changed drastically, yet it still has some artifacts, like callback functions that will never run, because new read-only mode was done.
So my proposal is to rewrite this plugin from ground up and try to not overthink every callback, just make the interface cleaner (see [my simple file browser](https://github.com/rvi64/files-plugin/blob/master/files.lua))

**Comment by sum01** [comment]
Yeah I know it needs to be done, but honestly I stopped using Micro except when testing PR's for this plugin, so it's not really my main priority.

See https://github.com/NicolaiSoeborg/filemanager-plugin/projects/1 for ideas on what needs to be done. The bulk of the work would be to creating a data structure that lets it quickly be read without hurting insert/removal times much. Some nice, clean OOP would help there, although Lua isn't my favorite for that...
